### ISSUE TITLE
Cannot deploy bind9 in dynamic network

### ISSUE THREAD

**Issue by miro-grapeup** [cloudfoundry-community/bind9-boshrelease#13]
In cloud config I have defined network:
```
- name: net
  type: dynamic
  subnets:
  - az: z1
    cloud_properties:
      subnet: ((net_id_1))
  - azs: [z2]
    cloud_properties:
      subnet: ((net_id_2))
```

And now when I try to deploy bind9 using this network it fails because in the `also-notify` we got domain address instead of IP:
`also-notify    { 04a81a10-49b1-4538-9e5b-e93b9a77e29a.slave.net.dns.bosh; };`

This is done by https://github.com/cloudfoundry-community/bind9-boshrelease/blob/master/jobs/master/templates/config/master.conf#L32 `link` which returns DNS domain and acording to bosh spec we cannot change it, even with `ip_addresses` set to true:
```
ip_addresses [Boolean]: Instructs the director to use ip addresses instead of DNS names. This property is ignored in the case of dynamic networks, which always use DNS addresses. Defaults to false. See dns for more details.
```

----
bosh-dns config is the default one https://github.com/cloudfoundry/bosh-deployment/blob/fa4b0a5602b67b370c14de9b5ac387e4cdfead76/runtime-configs/dns.yml
