### ISSUE TITLE
bug: allow using bind9-boshrelease without defining zones

### ISSUE THREAD

**Issue by lrstanley** [cloudfoundry-community/bind9-boshrelease#19]
Currently, when one doesn't define a zone in the deployment manifest, bind9 fails with something along the lines of:

```
usage: named-checkzone [...] /some/path/*.db
```

Because there are no files for it to check is why it fails. Adding a zone, and it works without issue.

The issue seems to be with:

https://github.com/cloudfoundry-community/bind9-boshrelease/blob/master/jobs/named/templates/bin/named#L42-L49

I believe bash will still invoke the for loop, with an empty variable, because no files are found.

----------

Problem is, bind9 is useful to use as a form of DNS caching. Other alternatives don't seem to work consistently:

- bosh-dns requires cert generation, which requires credhub. On some of our bosh deployments which are bare (not managed by opsman), they don't have credhub setup, so the cert management is a huge pain (it's also undocumented). It's also overkill if we don't need local service discovery, and just want a cache for external resolvers.
- consul seems to have issues caching with some kinds of hosts, in addition to it being overkill for just caching external resolvers.

Here is our config right now:
```yaml
  jobs:
  [...]
  - name: named
    release: bind9
    properties:
      zones:
        10.in-addr.arpa: |+
          $TTL 1h
          $ORIGIN 10.in-addr.arpa.
          @ IN SOA <some-random-zone because it needs one to start>
      bind_options:
        forward: "only"
        dnssec-validation: "yes"
      recursion:
        allow_from: ["1.2.3.4/27", "localhost", "localnets"]
        forwarders: [1.1.1.1, 2.2.2.2, 3.3.3.3, 4.4.4.4]
```

I would like to cut out the entire zones property if possible, thoughts?
